### ISSUE TITLE
De-lambda-ize yaml config

### ISSUE THREAD

**Issue by loongyh** [loongyh/esphome-fingerprint#17]
@OnFreund On further testing, the yaml config became heavily lambda-dependent, with lambdas for almost every trigger and action. Especially when trying to set the aura LED pattern based on a finger scan result.

Current implementation of the FingerScannedTrigger with passed-in uint8_t variables directly from the FP lib will mean the user have to understand the internal code, i.e. the FP lib's `FINGERPRINT_` constants to use said variables. AFAIK there's no other way to retrieve trigger variables aside from lambdas. It quickly becomes a mess, see my current config below:

```
rxxx:
  on_finger_scanned:
    - rxxx.aura_led_control:
        state: !lambda "if (result == FINGERPRINT_OK) return FINGERPRINT_LED_BREATHING; else return FINGERPRINT_LED_FLASHING;"
        speed: !lambda "if (result == FINGERPRINT_OK) return 200; else return 25;"
        color: !lambda "if (result == FINGERPRINT_OK) return FINGERPRINT_LED_BLUE; else return FINGERPRINT_LED_RED;"
        count: 2
    - lambda: |-
        switch (result) {
          case FINGERPRINT_OK:
            id(rxxx_state).publish_state("Authorized finger " + to_string(finger_id));
            break;
          case FINGERPRINT_PACKETRECIEVEERR:
            id(rxxx_state).publish_state("Communication error");
            break;
          case FINGERPRINT_NOTFOUND:
            id(rxxx_state).publish_state("Unauthorized finger");
            break;
          default:
            id(rxxx_state).publish_state("Unknown error: " + to_string(result));
        }
```

I recommend we split the FingerScannedTrigger into FingerScanMatchedTrigger<uint16_t finger_id, uint16_t confidence> and FingerScanUnmatchedTrigger<>. This way the user does not have to drop to lambda to use the variables to set the LED or unlock a lock etc.

**Comment by loongyh** [comment]
New config in proposed change:
```
rxxx:
  on_finger_scan_matched:
    - rxxx.aura_led_control:
        state: BREATHING
        speed: 200
        color: BLUE
        count: 2
    - text_sensor.template.publish:
        id: rxxx_state
        state: "Authorized finger"
  on_finger_scan_unmatched:
    - rxxx.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 2
    - text_sensor.template.publish:
        id: rxxx_state
        state: "Unauthorized finger"
```
finger_id, confidence are still available in the lambda in the on_finger_scan_matched trigger, however since they're also published to the last_finger_id and last_confidence sensors, user can still use them without lambdas.

For the on_finger_scan_unmatched trigger, I'm recommending it should only trigger on `FINGERPRINT_NOTFOUND` result. Any other result are errors and shouldn't be in this trigger.
Likewise for the on_finger_scan_matched trigger, only `FINGERPRINT_OK` result should trigger it.
