### ISSUE TITLE
Enrollment workflow

### ISSUE THREAD

**Issue by loongyh** [loongyh/esphome-fingerprint#2]
HA UI to manipulate saved templates onboard FP reader flash.

Possible workflows:

1. Combination of sensors and switches:
   1. Toggle through template numbers using switches for prev and next buttons.
   2. Show the currently selected template slot via `selected_template_sensor`.
   3. CRUD operations on template in selected slot via switches.
   4. Trigger download using a switch, HTTP POST the template somewhere.
   5. Trigger upload using a switch, HTTP GET the template somewhere.
2. Implement a web UI using the web server component.

Create function already partly implemented with current EnrollmentTrigger.

**Comment by loongyh** [comment]
3. Direct number input through HA UI:
   1. Create Input Number entity `input_number.rxxx` in home assistant.
      ```
      input_number:
        rxxx:
          name: Slot No.
          icon: mdi:content-save
          min: 0
          max: 200
          mode: box
      ```
   2. Corresponding ESPHome YAML config.
      ```
      rxxx:
        input_num_id: hass_input_num
      binary_sensor:
        - platform: rxxx
          id: rxxx_enrolling
          name: "Rxxx Enrolling"
      sensor:
        - platform: homeassistant
          id: hass_input_num
          entity_id: input_number.rxxx
          accuracy_decimals: 0
      ```
   3. Use number from sensor as slot number in enrollment actions.
      ```
      switch:
        - platform: template
          name: "Rxxx Enroll"
          lambda: !lambda "return id(rxxx_enrolling).state;"
          turn_on_action:
            - rxxx.enroll:
                num_scans: 6
          turn_off_action:
            - rxxx.cancel_enroll:
      ```
